# Generated by Django 5.1.6 on 2025-02-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField()),
                ('tags', models.CharField(choices=[('écologie', 'Écologie'), ('politique', 'Politique'), ('numérique', 'Numérique'), ('santé', 'Santé')], default='écologie', max_length=50)),
            ],
        ),
    ]
