# Generated by Django 5.1.6 on 2025-02-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.TextField(default='Texte non disponible'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_fr',
            field=models.TextField(default='Texte non disponible'),
        ),
    ]
